Add badges management to organization view
developmentseed/osm-teams pull request #256
Opened 2022-03-11 12:39 UTC by vgeorge

## What I am changing

Adds the ability to manage badges in the organization page.

## How I did it

This is WIP. Tasks:

- [X] Add badges table to organization view
- [X] Load badges from the API
- [ ] Handle error/loading state for badges
- [ ] Add badge action 
- [ ] Edit badge action
- [ ] Delete badge action

This also includes a small lib `api-client.js` to avoid code repetition while interacting with the API.

## How you can test it

Run the development server and perform add/edit/remove badges actions.

## Related Issues

- #240

2022-03-23 12:39 UTC, vgeorge commented
@kamicut ready for review.

2022-04-07 18:45 UTC, vgeorge commented
@kamicut added a fix for the display name issues, please let me know if you can add members now.

2022-04-10 18:57 UTC, kamicut requested changes
There is a 401 Unauthorized error that appears on the main organization dashboard when getting the badges for a user that is not part of an organization. This causes the page to error out to 401. We should catch the 401 and fail silently since it's an expected behavior, or delay the "get badges" call until we know the user has the correct permissions (if they are part of the owners list)

I recommend creating a second OSM user @vgeorge to test this type of behavior.

Otherwise, the PR is good to merge once this is fixed.

2022-04-11 10:24 UTC, kamicut approved these changes

2022-04-11 10:24 UTC, merged